app/styles/hypertable.less
app/templates/components/hyper-table.hbs

Allows for two possibilities:
`inverse block` presence => the inverse block is used as empty state
`inverse block` missing => the default message is displayed

Add support for empty state

---

addon/components/hyper-table.js
app/templates/components/hyper-table.hbs
app/templates/components/hyper-table/views.hbs

Clicking outside actual rows doesn't trigger the focus out triggering dropdown closing.
To fix that, modifier `{{on-click-outside}}` is used
Related to : https://github.com/upfluence/backlog/issues/266
Closing work

Hypertable: click outside don't work

---

app/templates/components/hyper-table.hbs

Pass the variable allRowsSelected to contextual action, it is needed to detect whether a user wants to delete all influencers from the IRM or a few
Related to https://github.com/upfluence/backlog/issues/490
None

Pass allRowsSelected variable to contextual actions

---

addon/mixins/filters-renderer.js
app/templates/components/hyper-table/column.hbs
app/templates/components/hyper-table/facetting.hbs
app/templates/components/hyper-table/filters-renderers/date.hbs
app/templates/components/hyper-table/filters-renderers/money.hbs
app/templates/components/hyper-table/filters-renderers/numeric.hbs
app/templates/components/hyper-table/filters-renderers/text.hbs

This PR adds `data-control-name` entries to filters menus.
Related to: https://github.com/upfluence/backlog/issues/657

Add filter data control name to filters menus

---

addon/components/hyper-table.js

Fixes collection.length triggered too early before the collection is ready.
Related to : https://sentry.io/organizations/upfluence/issues/2450648452/?project=5550971&query=is%3Aunresolved

Safely navigate to collection's length

---

addon/mixins/filters-renderer.js
app/templates/components/hyper-table/column.hbs

Apply the click-outside handler on the `.available-filters` class so it works on Tether portals.
Related to : https://github.com/upfluence/cs/issues/156

Fix click-outside being applied too aggressively 

---

.eslintrc.js
.prettierrc
addon/components/hyper-table/filters-renderers/numeric.js

Fixes issue requiring both minimum and maximum values in a numerical filter
Related to : https://github.com/upfluence/cs/issues/79
User can enter only a minimum or a maximum when filtering by a number

Fix numeric filter bounds

---

addon/components/hyper-table.js

Fixes issue where table refreshes every time a user toggles a column visibility
Related to: https://app.zenhub.com/workspaces/engineering-60b8ff993afa1f000e7c1d9c/issues/upfluence/cs/223
Columns will toggle correctly

Fix columns visibility issue

---

addon/components/hyper-table.js
addon/components/hyper-table/facetting.js
app/templates/components/hyper-table/cell-renderers/list.hbs
app/templates/components/hyper-table/cell-renderers/money.hbs
app/templates/components/hyper-table/cell-renderers/numeric.hbs
app/templates/components/hyper-table/cell-renderers/text.hbs
app/templates/components/hyper-table/column.hbs
app/templates/components/hyper-table/facetting.hbs
app/templates/components/hyper-table/views/view.hbs

Uses the `enable-tooltip` where needed and gets rid of `this.$('[data-tooltip]')` usage (removes a bunch of deprecation warnings)

Use  modifier everywhere

---

addon/components/hyper-table/column.js
addon/types/store.js
addon/types/table.js
tests/integration/components/hyper-table/store-test.js

Store both fields and columns in the storage.
Related to : https://github.com/upfluence/backlog/issues/933

Rework Local Storage store & relationship between field and column

---

addon/components/hyper-table.js
app/templates/components/hyper-table.hbs

Allow a custom search component to be passed in place of the Search Input. Allowed values are:
* string : path to the component
* `component instance` (using the `component` helper) 

Add support for a passing custom search component

---

addon/components/hyper-table/cell-renderers/image.js
app/templates/components/hyper-table/cell-renderers/image.hbs
testem.js
tests/integration/components/hyper-table/cell-renderers/image-test.js

Add support for notification dot on the image cell renderer.
Related to : https://github.com/upfluence/cs/issues/323

Support notification dot on image cell renderer

---

app/styles/header.less
app/styles/inner-table.less

Set up right stacking context. 
Context:
- The `hypertable__sticky-columns` has a `z-index: 20`
- The side-panel has a `z-index: 21`
They share the same stacking context because any other z-index is defined in parent component
Goal:
Set `z-index` to header and table to fix display order
To display a dropdown in contextual action, a stacking need to be defined for hypertable to display section (header, table) in the right order. This is not affect the side-panel display.
Link to [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_context_example_1)
Related to : https://github.com/upfluence/backlog/issues/1093
* Feel free to migrate existing …

Set up right stacking context

---

addon-test-support/table-manager.ts
addon/components/hyper-table-v2/index.hbs
addon/components/hyper-table-v2/index.ts
tests/integration/components/hyper-table-v2-test.ts

Add reset filters button
Related to : https://github.com/upfluence/backlog/issues/901

Add reset filters button

---

app/styles/cells.less
app/styles/columns.less
app/styles/inner-table.less
tests/integration/components/hyper-table-v2-test.ts

Fixes overlapping columns in the table which used to created an extra 2px width that lead to showing a scrollbar when unwanted.

Fixed: Overlapping Columns and unwanted scrollbar

---

addon/components/hyper-table-v2/filtering-renderers/common/ordering.hbs
addon/components/hyper-table-v2/filtering-renderers/common/ordering.ts
addon/components/hyper-table-v2/filtering-renderers/date.hbs
addon/components/hyper-table-v2/filtering-renderers/date.ts
addon/components/hyper-table-v2/filtering-renderers/numeric.hbs
addon/components/hyper-table-v2/filtering-renderers/numeric.ts
addon/components/hyper-table-v2/filtering-renderers/text.hbs
addon/components/hyper-table-v2/filtering-renderers/text.ts
app/components/hyper-table-v2/filtering-renderers/common/ordering.js
tests/integration/components/hyper-table-v2/filtering-renderers/common/ordering-test.ts

Refactored Date, Text & Numeric Filter renderers
Created Ordering component for filter renderers that is located in the filter-renderers/common folder
Refactored Text, Date & Numeric filter renderers to use this new component
Added tests for this component

Added: Ordering component for filter renderers

---

addon/components/hyper-table-v2/filtering-renderers/common/search.hbs
addon/components/hyper-table-v2/filtering-renderers/common/search.ts
addon/components/hyper-table-v2/filtering-renderers/text.hbs
addon/components/hyper-table-v2/filtering-renderers/text.ts
app/components/hyper-table-v2/filtering-renderers/common/search.js
tests/integration/components/hyper-table-v2/filtering-renderers/common/search-test.ts
tests/integration/components/hyper-table-v2/filtering-renderers/text-test.ts

Refactored Date, Text & Numeric Filter renderers
Created Search component for filter renderers that is located in the filter-renderers/common folder
Refactored Text filter renderers to use this new component
Added tests for this component

Added: Search Common component for filter renderers

---

addon-test-support/table-manager.ts
addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.ts
addon/core/interfaces/column.ts
addon/core/rendering-resolver.ts
tests/dummy/app/controllers/application.ts
tests/integration/components/hyper-table-v2/filtering-renderers/common/facets-loader-test.ts
tests/integration/components/hyper-table-v2/manage-columns-test.ts
tests/unit/core/handler-test.ts

Integrate the addition of the Descriptors in the column definitions
* Data models have been updated
* The FacetLoader component has been updated to use the faceting_by key provided in the column definition or to default back to "value" if nothing exists.

Integrate the addition of the Descriptors in the column definitions

---

addon/components/hyper-table-v2/filtering-renderers/numeric.ts
tests/integration/components/hyper-table-v2/filtering-renderers/numeric-test.ts

Fix display of to and from value in numeric filter
Related to : https://github.com/upfluence/backlog/issues/1297

Fix display of to and from value in numeric filter

---

addon/components/hyper-table-v2/filtering-renderers/date.ts
addon/core/handler.ts
app/styles/inner-table.less
tests/unit/core/handler-test.ts

Add apply-filter trigger event. It is using in the threads stats footer to re-call stats after a change
Related to : https://github.com/upfluence/backlog/issues/1314

Add apply-filter trigger event

---

addon/components/hyper-table-v2/filtering-renderers/common/existence.ts
tests/integration/components/hyper-table-v2/filtering-renderers/common/existence-test.ts

This PR adds `filteringKey` argument to the `existence filter` as this kind of filter could be used for another filtering key.
It should be renamed to `RadioButton` filter, though for compatibility sake, we're not going to do this just yet. 
Related to : https://github.com/upfluence/backlog/issues/1368

filters/common/existence: allow passing down a filtering key

---

addon/components/hyper-table-v2/search.ts

Use filterable_by from the column definition when available and default to 'value' if none exist.
Also listen for 'reset-columns' from the handler to reset the search filter.
Related to : #[1357](https://github.com/upfluence/backlog/issues/1357)

Added: Search now uses column definition attribute if it exists

---

addon/components/hyper-table-v2/column.hbs
addon/components/hyper-table-v2/column.ts
addon/components/hyper-table-v2/manage-columns.ts
tests/integration/components/hyper-table-v2/filtering-renderers/numeric-test.ts
tests/integration/components/hyper-table-v2/manage-columns-test.ts

Hide the first column from the Manage Fields component
Related to : #[1365](https://github.com/upfluence/backlog/issues/1356)

Hide the first column from the Manage Fields component

---

addon/components/hyper-table-v2/index.ts
addon/components/hyper-table-v2/manage-columns.hbs
addon/components/hyper-table-v2/manage-columns.ts
addon/core/handler.ts

* Fixed mutli call on load, column add/remove + onBottomReached
* Debounce reset filters button
* Added loading state on ManageField Column Add/Remove buttons
* Fixed multi calls on ManageField column button press
Related to : #[1348](https://github.com/upfluence/backlog/issues/1348)

Fix hypertable performance issues

---

addon/components/hyper-table-v2/filtering-renderers/date.hbs
addon/components/hyper-table-v2/filtering-renderers/date.ts

Remove flatpickrRef. `flatpickrRef` is useless because when we reset filter, the filter is re-render with the correct value. 
Related to : https://github.com/upfluence/backlog/issues/1392

Remove flatpickrRef in date filter

---

addon/components/hyper-table-v2/filtering-renderers/date.ts
tests/integration/components/hyper-table-v2/filtering-renderers/date-test.ts

This PR fixes the date filters logic:
- It sets the proper key `moving`
- It makes the `moving` and `range` filtering exclusive.
Related to : https://github.com/upfluence/backlog/issues/1391

filtering-renderers/date: fix filter application

---

addon/components/hyper-table-v2/search.ts
addon/core/handler.ts

* handler.resetRows now trigger an event
* Fixed double call issue when clicking on reset-filters button
Related to : #[1393](https://github.com/upfluence/backlog/issues/1393)

Trigger event on Handler.resetRows 

---

addon/components/hyper-table-v2/index.hbs
addon/components/hyper-table-v2/index.ts
addon/core/handler.ts
tests/integration/components/hyper-table-v2-test.ts

display the number of selected rows in the table
Related to : #

Display the number of selected rows in the header

---

.github/pull_request_template.md
addon-test-support/rows-fetcher.ts
addon/core/handler.ts
tests/unit/core/handler-test.ts

Add `removeRow` method for handler to remove row by record Id
Related to : https://github.com/upfluence/backlog/issues/1451

Add removeRow for handler

---

addon-test-support/table-manager.ts
addon/components/hyper-table-v2/column.ts
addon/components/hyper-table-v2/filtering-renderers/common/column-actions.ts
addon/components/hyper-table-v2/index.hbs
addon/components/hyper-table-v2/manage-columns.ts
addon/core/handler.ts
addon/core/interfaces/column.ts
tests/integration/components/hyper-table-v2/filtering-renderers/common/column-actions-test.ts
tests/integration/components/hyper-table-v2/manage-columns-test.ts

Base the column stickiness on an actual boolean on the definition instead of the column position. This allows us to handle multiple sticky columns easier.
Related to : https://github.com/upfluence/backlog/issues/1454

Handle the sticky columns better

---

addon/components/hyper-table-v2/index.hbs
app/styles/columns.less

Position sticky columns with higher z-index
- [x ] Is against the correct branch

position sticky columns over other ones

---

addon/components/hyper-table-v2/cell-renderers/text.hbs
addon/components/hyper-table-v2/cell-renderers/text.ts
tests/integration/components/hyper-table-v2/cell-renderers/text-test.ts

Make sure the text cells have an ellipsis by default depending on their column's size
Related to: 
- https://github.com/upfluence/backlog/issues/1536
- https://github.com/upfluence/backlog/issues/1541

Add a default ellipsis on the text cells depending on their size

---

addon/components/hyper-table-v2/index.hbs
addon/components/hyper-table-v2/index.ts
addon/components/hyper-table-v2/search.ts

Search input is now filled on reload
Related to : #[1561](https://github.com/upfluence/backlog/issues/1561)

Search input is now filled on reload

---

app/styles/hypertable.less

Update hypertable-summary for small screen. `hypertable-footer` doesn't exist in code base (old class)
Related to : cooldown

Update hypertable-summary for small screen

---

addon/core/handler.ts
tests/unit/core/handler-test.ts

Add refresh of rows for `removeColumn` and trigger `remove-column` event
Related to : https://github.com/upfluence/backlog/issues/1525

Fetch row after deleting a column

---

addon/core/handler.ts
tests/unit/core/handler-test.ts

This PR defines a way of changing a row content locally by its ID.
Related to : https://github.com/upfluence/backlog/issues/1594

core/handler: define mutateRow

---

app/styles/header.less

Available-fields-wrapper: add missing css class. It is now responsive.
Related to : https://github.com/upfluence/backlog/issues/1554

Available-fields-wrapper: add missing css class

---

addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.hbs
addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.ts

Prevent users from applying multiple facets at once on fast clicks
Related to : https://github.com/upfluence/backlog/issues/1526

Prevent users from applying multiple facets at once on fast clicks

---

addon/components/hyper-table/column.js

Destroy column filter when it is open in v1
Related to : https://github.com/upfluence/backlog/issues/1893

Destroy column filter when it is open in v1

---

addon/components/hyper-table-v2/filtering-renderers/common/column-actions.hbs
addon/components/hyper-table-v2/index.hbs
addon/components/hyper-table/cell-renderers/link.hbs
addon/components/hyper-table/filters-renderers/date.hbs
addon/components/hyper-table/filters-renderers/money.hbs
addon/components/hyper-table/filters-renderers/numeric.hbs
addon/components/hyper-table/filters-renderers/text.hbs
addon/components/hyper-table/index.hbs
addon/components/hyper-table/views.hbs
app/styles/cells.less
app/styles/columns.less

Remove upf-btn--small classes or usages of `size="sm"` OSS::Button 
Related to : https://github.com/upfluence/backlog/issues/1705

Remove upf-btn--small classes

---

addon-test-support/index.ts
addon-test-support/rows-fetcher.ts
addon/components/hyper-table-v2/index.hbs
addon/components/hyper-table-v2/index.ts
addon/components/hyper-table/index.js
addon/core/handler.ts
app/styles/columns.less
app/styles/inner-table.less
tests/integration/components/hyper-table-v2-test.ts
tests/unit/core/handler-test.ts

Hypertable v2 support new selection
Add tests
Related to : https://github.com/upfluence/backlog/issues/2319

Hypertable v2 support new selection

---

.github/workflows/ci.yml
addon/components/hyper-table-v2/cell.hbs
addon/components/hyper-table-v2/column.hbs
addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.hbs
addon/components/hyper-table-v2/filtering-renderers/common/search.hbs
addon/components/hyper-table-v2/manage-columns.hbs
addon/components/hyper-table-v2/search.hbs
addon/components/hyper-table-v2/selection.hbs
addon/components/hyper-table/cell-renderers/list.hbs
addon/components/hyper-table/cell-renderers/money.hbs
addon/components/hyper-table/cell-renderers/numeric.hbs
addon/components/hyper-table/cell-renderers/text.hbs
addon/components/hyper-table/cell.hbs
addon/components/hyper-table/column.hbs
addon/components/hyper-table/facetting.hbs
addon/components/hyper-table/index.hbs
addon/components/hyper-table/views/view.hbs
app/styles/cells.less
app/styles/columns.less
app/styles/header.less
package.json
tests/integration/components/hyper-table-v2/cell-test.ts
tests/integration/components/hyper-table-v2/filtering-renderers/common/search-test.ts
yarn.lock

- Run ci on prs and releases only
- migrate bare FA icons to `OSS::Icon` component 
- migrate bare skeletons to `OSS::Skeleton` component

Run ci on prs and releases only + migrate to component usages for icons & skeletons

---

addon/components/hyper-table/cell.js
package.json

Sentry fix in hypertable cell
Related to : https://linear.app/upfluence/issue/ENG-467/typeerror-cannot-read-properties-of-undefined-reading-get

Sentry fix in hypertable cell

---

addon/components/hyper-table/index.js

Adds the option on hypertableV1 to disableAutoResize functions by passing the `disableAutoResize` to true in the parameters. Default behavior is to allow it.

Added: disableAutoResize argument on HypertableV1

---

addon/components/hyper-table/index.hbs
app/styles/columns.less

Fix drag icon overlapping the filter trigger

Fix drag icon overlapping the filter trigger

---

addon/components/hyper-table-v2/search.hbs
addon/components/hyper-table-v2/search.ts
addon/components/hyper-table/index.hbs
addon/components/hyper-table/index.js
tests/dummy/app/templates/application.hbs
tests/integration/components/hyper-table-v2/search-test.ts
yarn.lock

Updates Hypertable V1 & V2 search inputs to show a magnifying glass icon
Update HypertableV2::Search component with a placeholder parameter, also added tests for this component.
Also gives V1 table's search the ability to clearSearch (fa-times icon)

Updated: hypertable V1 & V2 search inputs + V2 search component

---

addon/core/handler.ts
tests/unit/core/handler-test.ts

Prevent unecessary record refresh when the record is not loaded

Prevent unecessary record refresh when the record is not loaded

---

addon/components/hyper-table/column.js

Update filter first column offset
Related to : https://linear.app/upfluence/issue/ENG-1209/off-screen-filter-menu-in-table-with-only-2-columns

Update filter first column offset

---

addon/components/hyper-table/facetting.hbs

Facet rendering improvement. The method to build the faceting in the irm change for `_buildFacet` method declaring `facetRenderer`. Only `entity-object` filter renderer is affected.
Related to : https://linear.app/upfluence/issue/ENG-168/tooltip-replace-legacy-tooltips

[Cooldown] Facet rendering improvement

---

addon/core/handler.ts
tests/integration/components/hyper-table-v2-test.ts
tests/unit/core/handler-test.ts

Skip duplicated rows
Related to : https://linear.app/upfluence/issue/ENG-1945/skip-rowsfetcher-new-rows-that-are-already-in-the-table

Skip duplicated rows

---

package.json
pnpm-lock.yaml
tests/dummy/app/routes/application.ts
tests/integration/components/hyper-table-v2/column-test.ts
tests/integration/components/hyper-table-v2/filtering-renderers/common/column-actions-test.ts
tests/integration/components/hyper-table-v2/filtering-renderers/common/existence-test.ts
tests/integration/components/hyper-table-v2/filtering-renderers/common/facets-loader-test.ts
tests/integration/components/hyper-table-v2/filtering-renderers/common/search-test.ts
tests/integration/components/hyper-table-v2/filtering-renderers/date-test.ts
tests/integration/components/hyper-table-v2/filtering-renderers/numeric-test.ts
tests/integration/components/hyper-table-v2/filtering-renderers/text-test.ts
tests/integration/components/hyper-table-v2/manage-columns-test.ts
tests/integration/components/hyper-table-v2/search-test.ts

Related to : #[VEL-2179](https://linear.app/upfluence/issue/VEL-2179/upgrade-ember-intl-to-v6)

Ember-intl: Migrate to v6.4

---

addon/components/hyper-table/cell-renderers/money.hbs
package.json
pnpm-lock.yaml

Related to : #[VEL-2360](https://linear.app/upfluence/issue/VEL-2360/get-rid-of-ember-xselect)

XSelect: Remove dependency & replace usage

---

addon/components/hyper-table/index.js
addon/core/handler.ts
tests/unit/core/handler-test.ts

Reset selection when resetting all columns

Reset selection when resetting all columns

---

addon/components/hyper-table-v2/index.ts

Close the filter when scrolling inside the table

HypertableV2: Close the filter when scrolling inside the table

---

.gitignore
Makefile
index.js
package.json
pnpm-lock.yaml
scripts/generate_sonar_report
sonar-project.properties
tests/test-helper.ts

Enable sonarqube on hypertable

Enable sonarqube on hypertable

---

addon/components/hyper-table/filters-renderers/index.js

Related to : #[DRA-655](https://linear.app/upfluence/issue/DRA-655/date-of-firstlast-sale-generated-columns-cant-be-removed-from-filter)

Filter renderer: Update removeColumn action

---

addon/types/table.js

[Hypertable v1] Instead of relying on the presence of Tether in the global scope, import it explicitely from the packages. This was actually only working because the final apps had Tether in the global scope via ember-tether (which is removed in https://github.com/upfluence/ember-upf-utils/pull/397 and https://github.com/upfluence/facade-web/pull/597).

[VEL-3593]  Explicitely import Tether via ESM import instead of relying on global definition

---

addon/components/hyper-table/index.hbs
addon/components/hyper-table/index.js

On search / filter with no results, auto-scrolls back to the beginning of the table to display empty state correctly.
Related to : #[DRA-1532](https://linear.app/upfluence/issue/DRA-1532/irm-empty-state-not-displaying)

Fixed: IRM empty state not displaying correctly

---

addon/components/hyper-table/index.hbs

HypertableV1 - enable single row loading state from manager

HypertableV1 - enable single row loading state from manager

---

addon/components/hyper-table/filters-renderers/money.js

Fixes an issue where we send "NaN" in a string to the backend when entering a partial From / To filter in hypertable V1:
⚠️ Also FYI, it looks like the NumericFilterRenderer defined in `money.js` file (the file updated) is used by the numeric filter renderer instead of the code stored in `numeric.js`.
As this has been the case for the past 5 years, and that we are moving all instances of hypertables to use V2, I feel it's not worth spending time changing the code here.
It's a good thing to point it out and to keep it in our minds though 😇 
Fixes this sentry issue on the backend, there's probably one on the frontend sentry board as well, but I cannot point it out:
https://upfluence.sentry.io/issues/6088772288/?referrer=Linear

Fixed: prevent sending upper or lowerBound filter when no value is defined

---

addon/components/hyper-table-v2/index.hbs
addon/components/hyper-table-v2/index.ts

Related to : #[DRA-1968](https://linear.app/upfluence/issue/DRA-1968/improve-selectdeselect-cell-behaviour-in-hypertables)
https://www.loom.com/share/ff2a1ae924024cf09a09ea302f9c6eb2

Improved: select/deselect behavior on hypertableV2

---

addon-test-support/rows-fetcher.ts
addon/components/hyper-table-v2/cell-renderers/date.hbs
addon/components/hyper-table-v2/cell-renderers/numeric.hbs
addon/components/hyper-table-v2/cell-renderers/text.hbs
addon/components/hyper-table-v2/filtering-renderers/common/search.ts
addon/components/hyper-table-v2/filtering-renderers/date.ts
addon/components/hyper-table-v2/filtering-renderers/numeric.ts
addon/core/interfaces/column.ts
tests/integration/components/hyper-table-v2-test.ts
tests/integration/components/hyper-table-v2/cell-renderers/date-test.ts
tests/integration/components/hyper-table-v2/cell-renderers/numeric-test.ts
tests/integration/components/hyper-table-v2/cell-renderers/text-test.ts
tests/integration/components/hyper-table-v2/filtering-renderers/common/search-test.ts
tests/unit/core/handler-test.ts

hyper-table-v2/filtering-renderers/date: allow moving option key to be extended in case the backend the API expects a different value.

hyper-table-v2/filtering-renderers/date: allow moving option key to be extended

---

addon/components/hyper-table/cell-renderers/list.hbs
addon/components/hyper-table/cell-renderers/list.js
app/styles/cells.less
translations/en-us.yaml

Added locked state on list cell renderer

---

addon-test-support/table-manager.ts
addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.hbs
addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.ts
tests/integration/components/hyper-table-v2/filtering-renderers/common/facets-loader-test.ts
tests/unit/core/handler-test.ts

Add support for facets sorting in the `FacetsLoader` component. By default, we will sort the facets by `count` while allowing support for a `sortCompareFn` arg that can be provided by the parent context to sort differently.

Add support for facets sorting (default by count)

---

app/styles/columns.less
app/styles/hypertable.less
app/styles/inner-table.less

Add sticky columns responsiveness fix

Add sticky columns responsiveness fix

---

addon/components/hyper-table-v2/index.hbs
addon/components/hyper-table-v2/index.ts

Scope the css var for # of columns to the table. This fixes an issue where if you jump between multiple tables or have multiple ones in the same page, the last one rendered would win.

Scope the css var for # of columns to the table

---

addon/components/hyper-table/index.js
addon/mixins/editable.js

Related to : #[VEL-4506](https://linear.app/upfluence/issue/VEL-4506/httpsdeprecationsemberjscomv3xtoc-jquery-event)
🤞none🤞
Use vanilla js eventListener for `resize` & `scroll` on hypertable v1
Use vanilla js for `autofocus` editable inputs on hypertable v1 (Tested with lastname on IRM)

Fix deprecation: Remove this. &  usage from hypertable

---

addon/components/hyper-table-v2/filtering-renderers/date.ts
addon/components/hyper-table/filters-renderers/date.js
addon/core/interfaces/column.ts
tests/integration/components/hyper-table-v2/filtering-renderers/date-test.ts

Add timezone to moving filters on date filter renderers

Add timezone to moving filters on date filter renderers

---

addon/components/hyper-table-v2/manage-columns.hbs
addon/components/hyper-table-v2/manage-columns.ts

- Prevent race condition between search input's blur event & columns toggling click event
- Add prefix search icon for consistency

In ManageColumns, fix needed double-click when the user typed a keyword

---

app/styles/facetting.less

Related to : #[DRA-2183](https://linear.app/upfluence/issue/DRA-2183/increase-dropdown-height-for-filtering-in-hyper-table-v2)
During the analysis, and seen with Max and William, the necessary height for hypertable__facetting was 270px so the dropdown would reach the desired 352px height.
For whatever reason, during implementation I had to up this number to 285px to reach the 352px goal.
No idea why this is happening, so screenshot added for proof :woman_shrugging: 

Improved: increased dropdown height for filtering in V2

---

addon/components/hyper-table-v2/index.hbs
addon/core/handler.ts
addon/core/interfaces/rows-fetcher.ts
tests/unit/core/handler-test.ts

Related to : #[DRA-2421](https://linear.app/upfluence/issue/DRA-2421/shipping-address-reverts-to-facade-one-after-shortlisting-creator-in)
Usage example 
https://github.com/user-attachments/assets/6eb2cf63-3c16-4850-b85f-add1f0e24d3c

Hypertable v2: Single row loading state

---

addon/components/hyper-table-v2/filtering-renderers/numeric.hbs

Related to : #[DRA-2234](https://linear.app/upfluence/issue/DRA-2234/hyper-table-v2-from-to-filter-doesnt-work-when-values-are-set-using)
From-To filter now reacts to value change when clicking on the arrows
https://www.loom.com/share/b5c9a6b4ec724bfbaf7cb5bbd6666bbb

Fixed V2 From-To filter arrow use

---

addon/components/hyper-table-v2/column.hbs

Currently, when a column is draggable, it's whole content can be used as handle (including the rows' cells), leading to weird behaviours.
This PR ensures users can only drag a column by its header using ember-sortable's `sortable-handle` modifier.

Hypertable v2: use the header's column as draggable handle

---

addon/components/hyper-table-v2/index.hbs
addon/components/hyper-table-v2/index.ts
addon/core/handler.ts
tests/integration/components/hyper-table-v2-test.ts
tests/unit/core/handler-test.ts

Properly reset the handler instance props when the table is unmounted
Fixes an issue where when leaving a page that was displaying a table, the currentPage wouldn't be reset and the user would resume from the last page loaded.

Properly reset the handler instance props when the table is unmounted

---

addon/components/hyper-table-v2/index.ts
tests/integration/components/hyper-table-v2-test.ts

Related to : #[DRA-3012](https://linear.app/upfluence/issue/DRA-3012/display-contact-all-to-better-promote-outreach-plan)
The goal is to remove this issue where selection remains to `all` even if all rows are excluded 🙏 
https://github.com/user-attachments/assets/aa085e54-1690-465a-b035-c86207f384ef

Hypertable v2: Reset selection when rows are all excluded

---

addon/components/hyper-table-v2/filtering-renderers/common/existence.hbs
addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.hbs
addon/components/hyper-table-v2/filtering-renderers/common/ordering.hbs
addon/components/hyper-table-v2/filtering-renderers/common/search.hbs
addon/components/hyper-table-v2/filtering-renderers/date.hbs
addon/components/hyper-table-v2/filtering-renderers/numeric.hbs
addon/components/hyper-table/filters-renderers/date.hbs
addon/components/hyper-table/filters-renderers/money.hbs
addon/components/hyper-table/filters-renderers/numeric.hbs
addon/components/hyper-table/filters-renderers/text.hbs
package.json
pnpm-lock.yaml

Fix hypertable labels to match design
Related to : #
- [] Added/updated tests
- [] Added/updated documentation

Fix hypertable labels to match design

---

addon-test-support/index.ts
addon-test-support/setup-table.ts
addon/components/hyper-table-v2/column.hbs
addon/components/hyper-table-v2/column.ts
addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.hbs
addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.ts
addon/components/hyper-table-v2/index.hbs
addon/components/hyper-table-v2/index.ts
addon/core/handler.ts
app/styles/columns.less
tests/integration/components/hyper-table-v2-test.ts
tests/integration/components/hyper-table-v2/column-test.ts

Feature flag the following features: manage fields, filters reset, column filtering.
This will allow us to unlock more usages of the table where the parent apps want more control on the filtering behaviours by opting-out of the default UX.

Feature flag the following features: manage fields, filters reset, column filtering

---

addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.hbs
addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.ts
tests/integration/components/hyper-table-v2/filtering-renderers/common/facets-loader-test.ts
tests/integration/components/hyper-table/cell-renderers/image-test.js

Related to : #[dra-3650](https://linear.app/upfluence/issue/DRA-3650/hypertable-extension-groundwork-create-new-instagramstoriesaccess)

Updated facets loader to include radio button exclusive option
