- addon/components/hyper-table/filters-renderers/date.js
- app/templates/components/hyper-table.hbs
> Add more presets to date filters

- addon/components/hyper-table/cell-renderers/image.js
- addon/components/hyper-table/cell.js
- app/components/hyper-table/cell-renderers/image.js
- app/styles/inner-table.less
- app/templates/components/hyper-table.hbs
- app/templates/components/hyper-table/cell-renderers/image.hbs
Adds support for Image Columns.
Also supports additional labels placed next to the image itself
> Image cell renderer

- addon/components/hyper-table/filters-renderers/date.js
- app/templates/components/hyper-table/filters-renderers/date.hbs
- package.json
- yarn.lock
User can filter by a date or a range of dates
> Add fixed date range calendar

- addon/components/hyper-table/filters-renderers/text.js
- app/templates/components/hyper-table/filters-renderers/text.hbs
- tests/dummy/app/services/plans-fetcher.js
User can search for a word/phrase in a column
> Add string search filtering to table data

- addon/components/hyper-table.js
- addon/types/table.js
- app/styles/header.less
- app/templates/components/hyper-table.hbs
- tests/dummy/app/controllers/application.js
- tests/dummy/app/services/plans-fetcher.js
> Add categories to fields section

- app/styles/columns.less
- app/templates/components/hyper-table/column.hbs
> Add option for custom html tooltip in table headers

- addon/components/hyper-table.js
- app/styles/header.less
- app/templates/components/hyper-table.hbs
- app/templates/components/hyper-table/column.hbs
> Improve fields manager to display clusters instead of fields

- .github/CODEOWNERS
- .github/pull_request_template.md
- addon/components/hyper-table/filters-renderers/text.js
Fix infinite loading when search in text filter
Related to : https://github.com/upfluence/backlog/issues/304
- ~[ ] Added/updated tests~
- ~[ ] Added/updated documentation~
> Hypertable : fix infinite loading for text search

- app/templates/components/hyper-table.hbs
No need to pass the parameter as it is accessible through the table manager
Related to : #
None
> Revert "Pass allRowsSelected variable to contextual actions"

- app/templates/components/hyper-table.hbs
- app/templates/components/hyper-table/views.hbs
This PR adds a `data-control-name=` attributes where needed.
Related to : https://github.com/upfluence/backlog/issues/657
> templates/components: Add data-control-name attribute on row checkbox

- README.md
- addon/components/hyper-table.js
- addon/components/hyper-table/cell-renderers/link.js
- addon/components/hyper-table/cell.js
- addon/components/hyper-table/column.js
- addon/helpers/cell-rendering-inferer.js
- addon/types/table.js
- app/components/hyper-table/cell-renderers/link.js
- app/styles/cells.less
- app/templates/components/hyper-table.hbs
- app/templates/components/hyper-table/cell-renderers/date.hbs
- app/templates/components/hyper-table/cell-renderers/image.hbs
- app/templates/components/hyper-table/cell-renderers/link.hbs
- app/templates/components/hyper-table/cell-renderers/money.hbs
- app/templates/components/hyper-table/cell-renderers/numeric.hbs
- app/templates/components/hyper-table/cell-renderers/text.hbs
- app/templates/components/hyper-table/column.hbs
- package.json
Make more features configurable and add support for link type columns.
Related to : https://github.com/upfluence/backlog/issues/696
> More configurability

- app/templates/components/hyper-table.hbs
- index.js
Do not show the Reset Filters button if the filtering feature isn't on.
> Config based reset filter

- addon/components/hyper-table.js
This PR fixes the `_searchQuery` observer loop [explained here](https://github.com/upfluence/cs/issues/178#issuecomment-865788649) causing the infinite reload loop, by not using an observer but a computted setter instead, which sets the values of the filters as long as notifying that the `_searchQuery` has been updated.
It might be more efficient as it will save refresh triggers, as well as removing a debounce called with an anonymous function (which calls always twice the deboucned function).
Related to : https://github.com/upfluence/cs/issues/178#issuecomment-865788649
:warning: This commit introduces  a breaking change as now hypertables sets the filters array value of the first object itself. Please review this carefully.
> addon/components: use computed setter instead of an observer to notify changes

- app/templates/components/hyper-table.hbs
- translations/en-us.yaml
Adds i18n to the entry component and moves components syntax to Glimmer
Related to : https://github.com/upfluence/backlog/issues/786
> More i18n to the main component.

- app/styles/cells.less
- app/styles/header.less
Clean up scrollbar
Related to : https://github.com/upfluence/backlog/issues/1024
> Clean up scrollbar

- addon-test-support/index.ts
- addon-test-support/rows-fetcher.ts
- addon-test-support/table-manager.ts
- addon/core/handler.ts
- addon/core/interfaces/column.ts
- addon/core/interfaces/index.ts
- addon/core/interfaces/manager.ts
- addon/core/interfaces/rows-fetcher.ts
- tests/test-helper.ts
- tests/unit/core/handler-test.ts
Add TableHandler class for managing the lifecycle of the table.
Related to : https://github.com/upfluence/backlog/issues/1240
> Introduce new Table handler

- .eslintrc.js
- addon/components/hyper-table-v2/cell.hbs
- addon/components/hyper-table-v2/cell.ts
- addon/components/hyper-table-v2/index.hbs
- app/components/hyper-table-v2/cell.js
- package.json
- tests/integration/components/hyper-table-v2/cell-test.ts
- yarn.lock
Adds a component representing a single cell in the table. That component is in charge of looking up the right component to display the content of the cell.
Related to : https://github.com/upfluence/backlog/issues/1264
> Add Cell rendering component

- .github/workflows/ci.yml
- addon-test-support/table-manager.ts
- addon/components/hyper-table-v2/column.hbs
- addon/components/hyper-table-v2/column.ts
- addon/components/hyper-table-v2/filtering-renderers/text.hbs
- addon/components/hyper-table-v2/filtering-renderers/text.ts
- addon/components/hyper-table-v2/index.hbs
- addon/core/handler.ts
- addon/core/interfaces/column.ts
- addon/core/interfaces/index.ts
- addon/core/interfaces/rendering-resolver.ts
- addon/core/rendering-resolver.ts
- app/components/hyper-table-v2/filtering-renderers/text.js
- app/styles/columns.less
- app/styles/inner-table.less
- package.json
- tests/dummy/app/controllers/application.ts
- tests/dummy/config/environment.js
- tests/integration/components/hyper-table-v2/column-test.ts
- tests/integration/components/hyper-table-v2/filtering-renderers/text-test.ts
- tests/unit/core/handler-test.ts
- translations/en-us.yaml
- yarn.lock
Bring back support for filtering w/ the text type.
Related to : https://github.com/upfluence/backlog/issues/1263
> Filters rendering

- addon-test-support/table-manager.ts
- addon/components/hyper-table-v2/index.hbs
- addon/components/hyper-table-v2/index.ts
- addon/core/handler.ts
- tests/unit/core/handler-test.ts
Bring back the support for infinite scrolling.
Related to : https://github.com/upfluence/backlog/issues/1265
> Infinite scroll support

- addon/components/hyper-table-v2/index.hbs
- addon/components/hyper-table-v2/index.ts
- addon/components/hyper-table-v2/manage-columns.hbs
- addon/components/hyper-table-v2/manage-columns.ts
- app/styles/header.less
- tests/dummy/app/controllers/application.ts
- tests/dummy/app/templates/application.hbs
- tests/integration/components/hyper-table-v2-test.ts
- translations/en-us.yaml
- yarn.lock
Adds a default search input enabled/disabled in the FeatureSet.
Adds a <:search> named-block in order to pass a custom search component
Adds tests :-)
> Handle default search feature + search named-block

- addon-test-support/table-manager.ts
- addon/core/handler.ts
- addon/core/interfaces/index.ts
- addon/core/interfaces/manager.ts
- tests/unit/core/handler-test.ts
Add support for facetting to the handler and table manager.
Related to : https://github.com/upfluence/backlog/issues/1322
> Add facetting support

- .github/workflows/ci.yml
- addon/components/hyper-table-v2/index.hbs
- addon/components/hyper-table-v2/index.ts
- addon/core/handler.ts
- tests/dummy/app/controllers/application.ts
- tests/integration/components/hyper-table-v2-test.ts
- tests/unit/core/handler-test.ts
add events support to react to particular things happening on the table lifecycle.
> Add support for events

- addon-test-support/rows-fetcher.ts
- addon-test-support/table-manager.ts
- addon/components/hyper-table-v2/cell-renderers/numeric.hbs
- addon/components/hyper-table-v2/cell-renderers/numeric.ts
- addon/components/hyper-table-v2/filtering-renderers/numeric.hbs
- addon/components/hyper-table-v2/filtering-renderers/numeric.ts
- addon/core/rendering-resolver.ts
- addon/helpers/custom-format-number.js
- app/components/hyper-table-v2/cell-renderers/numeric.js
- app/components/hyper-table-v2/filtering-renderers/numeric.js
- app/helpers/custom-format-number.js
- tests/dummy/app/controllers/application.ts
- tests/integration/components/hyper-table-v2-test.ts
- tests/integration/components/hyper-table-v2/cell-renderers/numeric-test.ts
- tests/integration/components/hyper-table-v2/filtering-renderers/numeric-test.ts
- tests/integration/components/hyper-table-v2/filtering-renderers/text-test.ts
- tests/unit/core/handler-test.ts
- translations/en-us.yaml
Adds Numeric Cell & Filter Renderers to HypertableV2
Related to : [#1311](https://github.com/upfluence/backlog/issues/1311)
> Added: Numeric Cell & Filter Renderers

- addon/components/hyper-table-v2/cell.hbs
- addon/components/hyper-table-v2/cell.ts
- addon/components/hyper-table-v2/index.hbs
- addon/components/hyper-table-v2/index.ts
- tests/integration/components/hyper-table-v2-test.ts
- tests/integration/components/hyper-table-v2/cell-test.ts
Hover state on rows
Related to : https://github.com/upfluence/backlog/issues/1308
> Hover state on rows

- addon/components/hyper-table-v2/filtering-renderers/common/existence.hbs
- addon/components/hyper-table-v2/filtering-renderers/common/existence.ts
- addon/components/hyper-table-v2/filtering-renderers/common/ordering.hbs
- addon/components/hyper-table-v2/filtering-renderers/numeric.hbs
- addon/components/hyper-table-v2/filtering-renderers/numeric.ts
- addon/components/hyper-table-v2/filtering-renderers/text.hbs
- app/components/hyper-table-v2/filtering-renderers/common/existence.js
- tests/integration/components/hyper-table-v2/filtering-renderers/common/existence-test.ts
Refactored Date, Text & Numeric Filter renderers
Created Existence component for filter renderers that is located in the filter-renderers/common folder
Refactored Numeric filter renderers to use this new component
Added tests for this component
+minor UI tweaks
> Added Common Existence component filter renderer

- addon/components/hyper-table-v2/index.hbs
- app/styles/columns.less
Fix glitch when swapping columns' order
> Fix glitchy column swap

- addon/components/hyper-table-v2/index.hbs
Fix checkbox column disappear
Related to : https://github.com/upfluence/backlog/issues/1297
> Fix checkbox column disappear

- addon/components/hyper-table-v2/filtering-renderers/date.hbs
- addon/components/hyper-table-v2/filtering-renderers/numeric.hbs
Fixed: moved column actions out of filterable condition
> Fixed: moved column actions out of filterable condition

- app/styles/hypertable.less
- yarn.lock
Add generic class for hypertable summary
Related to : https://github.com/upfluence/backlog/issues/1448
> Add generic class for hypertable summary

- addon/components/hyper-table/views.hbs
- addon/components/hyper-table/views.js
- addon/components/hyper-table/views/view.hbs
- translations/en-us.yaml
Rework modal-view to modal dialog
Related to (nothing)
> Rework modal-view to modal dialog

- addon/components/hyper-table-v2/filtering-renderers/common/existence.hbs
- tests/integration/components/hyper-table-v2/filtering-renderers/common/existence-test.ts
- tests/integration/components/hyper-table-v2/filtering-renderers/numeric-test.ts
- yarn.lock
existence filters: use the new OSS::RadioButton component
Related to : https://github.com/upfluence/backlog/issues/1399
> existence filters: use the new OSS::RadioButton component

- addon/components/hyper-table-v2/filtering-renderers/date.hbs
- addon/components/hyper-table/cell-renderers/date.hbs
- addon/components/hyper-table/cell-renderers/date.js
- addon/components/hyper-table/filters-renderers/date.hbs
- addon/components/hyper-table/filters-renderers/date.js
- package.json
- yarn.lock
> Bump ember-flatpickr

- addon/components/hyper-table/views.js
Select default view after it's been added
Related to : https://github.com/upfluence/backlog/issues/2205
> Select default view after it's been added

- addon/components/hyper-table-v2/selection.hbs
- addon/components/hyper-table-v2/selection.ts
- app/components/hyper-table-v2/selection.js
- app/styles/hypertable.less
- app/styles/selection.less
- tests/dummy/app/controllers/application.ts
- tests/dummy/app/templates/application.hbs
- tests/integration/components/hyper-table-v2/selection-test.ts
- translations/en-us.yaml
- yarn.lock
Add HyperTableV2::Selection component:
- implement it
- add tests
- add demo in `application.hbs`
Related to : https://github.com/upfluence/backlog/issues/2317
> HyperTableV2::Selection component

- app/styles/header.less
Update contextual action header
Related to : https://github.com/upfluence/backlog/issues/2333
Before/After:
> Update contextual action header

- addon/components/hyper-table-v2/selection.hbs
- addon/components/hyper-table/index.hbs
- addon/components/hyper-table/index.js
- addon/types/table.js
- app/styles/cells.less
- app/styles/columns.less
- app/styles/header.less
- app/styles/hypertable.less
- app/styles/inner-table.less
- app/styles/selection.less
- package.json
- translations/en-us.yaml
- tsconfig.json
- yarn.lock
Hypertable v1 with partial selection:
- Add selection component
- Change logic for selection
- Update less var to css var
Related to : https://github.com/upfluence/backlog/issues/2318
> Hypertable v1 with partial selection

- addon/components/hyper-table/index.js
Fix bug for select all feature
Related to : https://github.com/upfluence/backlog/issues/2322
> Fix bug for select all feature

- addon/components/hyper-table/index.hbs
- addon/components/hyper-table/index.js
- addon/types/table.js
- tests/integration/components/hyper-table-v2-test.ts
Migrate data from hypertable to manager
Related to : https://github.com/upfluence/backlog/issues/2325
> Migrate data from hypertable to manager

- app/styles/columns.less
- app/styles/facetting.less
- app/styles/footer.less
- app/styles/header.less
- app/styles/hypertable.less
Clean up some less variables
Related to : #
> Clean up some less variables

- addon/mixins/filters-renderer.js
Fix irresponsive column removal button
> Fix irresponsive column removal button

- addon-test-support/rows-fetcher.ts
- addon/components/hyper-table-v2/manage-columns.hbs
- addon/components/hyper-table/index.hbs
- addon/core/handler.ts
- addon/core/interfaces/rows-fetcher.ts
- tests/integration/components/hyper-table-v2/manage-columns-test.ts
- tests/unit/core/handler-test.ts
Add support for fetching a single record by id
> Add support for fetching a single record by id

- addon/components/hyper-table-v2/cell-renderers/text.ts
Dynamically watch for changes on the text columns
> Dynamically watch for changes on the text columns

- addon/components/hyper-table/index.js
Fixed: tableV1 search filtering
> Fixed: tableV1 search filtering

- addon/components/hyper-table-v2/index.hbs
- addon/components/hyper-table-v2/index.ts
- addon/components/hyper-table/index.hbs
- addon/components/hyper-table/index.js
- package.json
- yarn.lock
ember-sortable: set groupName attr to better handle cases w/ multiple table instances.
See https://github.com/adopted-ember-addons/ember-sortable#multiple-ember-sortables-renders-simultaneously for details.
> ember-sortable: set groupName attr to better handle cases w/ multiple table instances

- addon/components/hyper-table-v2/header-renderers/base.hbs
It fixes the overflow without ellipsis in hypertable cell headers , with visual test from linking hypertable to upfluence-web locally ( cf loom video ) .
Related to : #
https://linear.app/upfluence/issue/DRA-34/handle-workflow-hypertable-columns-with-long-titles
**Before on staging vs after on local with this fix**
https://linear.app/upfluence/issue/DRA-34/handle-workflow-hypertable-columns-with-long-titles
https://www.loom.com/share/81d36e2a02914c5ab01857c42c29b6c3?sid=3a0e94bc-828e-44e9-9f58-62233f5db952
Useful Resource : [Ember Octane vs Classic Cheat …
> Fix to missing ellipsis class on Cell headers

- app/styles/cells.less
https://www.loom.com/share/2afbe6a37b2442c98e4dec7a757b1a53?sid=0d9c99df-27fc-4c6e-8101-bd6ce0667748
Related to : #
https://linear.app/upfluence/issue/DRA-58/irm-hover-broken-email-column
> fix: removed bg color on email cell

- addon/components/hyper-table-v2/manage-columns.ts
- tests/integration/components/hyper-table-v2/manage-columns-test.ts
Update twitter clustering_key for x for manage columns
> Update twitter clustering_key for x for manage columns

- addon/components/hyper-table/facetting.js
- addon/components/hyper-table/filters-renderers/numeric.js
- addon/components/hyper-table/filters-renderers/text.js
- addon/components/hyper-table/index.js
- addon/components/hyper-table/views.js
- addon/mixins/cell-renderer.js
- addon/mixins/editable.js
Fixes: https://deprecations.emberjs.com/v3.x/#toc_deprecated-run-loop-and-computed-dot-access
> Fix "Run loop and computed dot access" deprecation

- addon/components/hyper-table-v2/index.hbs
- addon/components/hyper-table-v2/manage-columns.hbs
- app/styles/header.less
- tests/integration/components/hyper-table-v2-test.ts
- tests/integration/components/hyper-table-v2/filtering-renderers/common/facets-loader-test.ts
- translations/en-us.yaml
- Add support for table-actions named block
- Various style updates
> Add support for table-actions named block

- addon/core/handler.ts
> Updated toggleSelectAll method to nullify exclusion list

- addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.hbs
- addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.ts
- addon/components/hyper-table-v2/filtering-renderers/common/search.hbs
- addon/components/hyper-table-v2/filtering-renderers/common/search.ts
- addon/components/hyper-table-v2/manage-columns.hbs
- addon/components/hyper-table-v2/manage-columns.ts
- addon/components/hyper-table-v2/search.hbs
- addon/components/hyper-table-v2/search.ts
- package.json
- pnpm-lock.yaml
- tsconfig.json
Use search input in hypertable v2
No observable changes.
You can find the list of impacted functionnality here (green mark): https://linear.app/upfluence/project/standardize-search-input-behavior-across-the-platform-fe84f10abfdd/overview
> Use OSS SearchField in hypertable v2

- addon/components/hyper-table/index.hbs
- addon/components/hyper-table/index.js
Replaced Input Container in Manage Fields on Compensation table HypertableV1 by new Search Field component
Related to : #
> Replaced Input Container by Search Field

- .github/workflows/ci.yml
- addon/components/hyper-table-v2/filtering-renderers/common/existence.ts
- addon/components/hyper-table-v2/filtering-renderers/numeric.hbs
- addon/components/hyper-table-v2/filtering-renderers/numeric.ts
- tests/integration/components/hyper-table-v2/filtering-renderers/numeric-test.ts
> Updated numeric filter for v2

- addon/components/hyper-table-v2/manage-columns.hbs
- app/styles/header.less
- app/styles/hypertable.less
- app/styles/inner-table.less
- package.json
- pnpm-lock.yaml
> Border radius rework

- addon/components/hyper-table/views.hbs
Related to : #[VEL-4672](https://linear.app/upfluence/issue/VEL-4672/httpsdeprecationsemberjscomv3xtoc-ember-built-in-components-legacy)
> Deprecation: Fix built-in components legacy attributes
